### ISSUE TITLE
스터디 홈 API 구현

### ISSUE THREAD

**Issue by taeho0888** [solve-it3/server#12]
## Description
스터디 홈 API 구현
Todo 작성해주세요

## Todo
- [x] 모델 만들기
- [x] 스터디명 중복 API
- [x] 스터디 생성 API
- [x] 날짜 클릭시 문제와 멤버 보이는 API
- [x] 홈, 문제, 소셜, 설정 API
- [x] 진척도 API
- [x] 스터디 잔디 API
- [x] 스터디 바꾸기 알고리즘(페이지 변환)API

## ETC
기타사항
