### ISSUE TITLE
스터디 문제 API 구현

### ISSUE THREAD

**Issue by taeho0888** [solve-it3/server#13]
## Description
할 수 있다.

## Todo
- [x] #28
- [x] #29
- [x] 주차 날짜 보여주기
- [x] 해당 주차 보여주기
- [x] 해당 주차 알고리즘 보여주기
- [x] 문제 추가하기
- [x] 문제 번호, 이름 보여주기
- [x] 해당 문제 푼 사람 보여주기
- [x] 도전하기
- [x] 풀었습니다
- [x] 문제 삭제하기
- [ ] 스터디 삭제하기
- [ ] problemStatus 추가하기
- [ ] problemStatus 삭제하기
- [ ] 커밋 내역 추가하기
## ETC
기타사항
